version: "3.8"
services:
  users-service:
    build:
      context: .
      dockerfile: ./services/users/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - platform-network

networks:
  platform-network:
