// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: profiles.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Image         *File                  `protobuf:"bytes,5,opt,name=image,proto3,oneof" json:"image,omitempty"`
	AuthorProfile *Author                `protobuf:"bytes,6,opt,name=author_profile,json=authorProfile,proto3,oneof" json:"author_profile,omitempty"`
	Courses       []*Course              `protobuf:"bytes,7,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Profile) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *Profile) GetImage() *File {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Profile) GetAuthorProfile() *Author {
	if x != nil {
		return x.AuthorProfile
	}
	return nil
}

func (x *Profile) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type Author struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bio             string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Balance         int32                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	UserProfile     *Profile               `protobuf:"bytes,4,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	Accomplishments []*File                `protobuf:"bytes,5,rep,name=accomplishments,proto3" json:"accomplishments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Author) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Author) GetUserProfile() *Profile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *Author) GetAccomplishments() []*File {
	if x != nil {
		return x.Accomplishments
	}
	return nil
}

type Course struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	PaymentPriceId   string                 `protobuf:"bytes,5,opt,name=payment_price_id,json=paymentPriceId,proto3" json:"payment_price_id,omitempty"`
	PaymentProductId string                 `protobuf:"bytes,6,opt,name=payment_product_id,json=paymentProductId,proto3" json:"payment_product_id,omitempty"`
	Language         string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Level            string                 `protobuf:"bytes,8,opt,name=level,proto3" json:"level,omitempty"`
	Duration         uint64                 `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`
	Rate             float64                `protobuf:"fixed64,10,opt,name=rate,proto3" json:"rate,omitempty"`
	RatersCount      uint64                 `protobuf:"varint,11,opt,name=raters_count,json=ratersCount,proto3" json:"raters_count,omitempty"`
	IsCompleted      bool                   `protobuf:"varint,12,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	Video            *File                  `protobuf:"bytes,15,opt,name=video,proto3" json:"video,omitempty"`
	Image            *File                  `protobuf:"bytes,16,opt,name=image,proto3" json:"image,omitempty"`
	AuthorId         string                 `protobuf:"bytes,17,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Author           *Author                `protobuf:"bytes,18,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *Course) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Course) GetPaymentPriceId() string {
	if x != nil {
		return x.PaymentPriceId
	}
	return ""
}

func (x *Course) GetPaymentProductId() string {
	if x != nil {
		return x.PaymentProductId
	}
	return ""
}

func (x *Course) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Course) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Course) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Course) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Course) GetRatersCount() uint64 {
	if x != nil {
		return x.RatersCount
	}
	return 0
}

func (x *Course) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *Course) GetVideo() *File {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *Course) GetImage() *File {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Course) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Course) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	ThumbnailUrl  *string                `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *File) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *File) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddAccomplishmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAccomplishmentRequest) Reset() {
	*x = AddAccomplishmentRequest{}
	mi := &file_profiles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAccomplishmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccomplishmentRequest) ProtoMessage() {}

func (x *AddAccomplishmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccomplishmentRequest.ProtoReflect.Descriptor instead.
func (*AddAccomplishmentRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{5}
}

func (x *AddAccomplishmentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *AddAccomplishmentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AddAccomplishmentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type DeleteAccomplishmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccomplishmentRequest) Reset() {
	*x = DeleteAccomplishmentRequest{}
	mi := &file_profiles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccomplishmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccomplishmentRequest) ProtoMessage() {}

func (x *DeleteAccomplishmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccomplishmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccomplishmentRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAccomplishmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_profiles_proto protoreflect.FileDescriptor

const file_profiles_proto_rawDesc = "" +
	"\n" +
	"\x0eprofiles.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x02\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12%\n" +
	"\x05image\x18\x05 \x01(\v2\n" +
	".auth.FileH\x00R\x05image\x88\x01\x01\x128\n" +
	"\x0eauthor_profile\x18\x06 \x01(\v2\f.auth.AuthorH\x01R\rauthorProfile\x88\x01\x01\x12&\n" +
	"\acourses\x18\a \x03(\v2\f.auth.CourseR\acoursesB\b\n" +
	"\x06_imageB\x11\n" +
	"\x0f_author_profile\"\xac\x01\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x05R\abalance\x120\n" +
	"\fuser_profile\x18\x04 \x01(\v2\r.auth.ProfileR\vuserProfile\x124\n" +
	"\x0faccomplishments\x18\x05 \x03(\v2\n" +
	".auth.FileR\x0faccomplishments\"\xed\x03\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12(\n" +
	"\x10payment_price_id\x18\x05 \x01(\tR\x0epaymentPriceId\x12,\n" +
	"\x12payment_product_id\x18\x06 \x01(\tR\x10paymentProductId\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x14\n" +
	"\x05level\x18\b \x01(\tR\x05level\x12\x1a\n" +
	"\bduration\x18\t \x01(\x04R\bduration\x12\x12\n" +
	"\x04rate\x18\n" +
	" \x01(\x01R\x04rate\x12!\n" +
	"\fraters_count\x18\v \x01(\x04R\vratersCount\x12!\n" +
	"\fis_completed\x18\f \x01(\bR\visCompleted\x12 \n" +
	"\x05video\x18\x0f \x01(\v2\n" +
	".auth.FileR\x05video\x12 \n" +
	"\x05image\x18\x10 \x01(\v2\n" +
	".auth.FileR\x05image\x12\x1b\n" +
	"\tauthor_id\x18\x11 \x01(\tR\bauthorId\x12$\n" +
	"\x06author\x18\x12 \x01(\v2\f.auth.AuthorR\x06author\"\x92\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12(\n" +
	"\rthumbnail_url\x18\x06 \x01(\tH\x00R\fthumbnailUrl\x88\x01\x01B\x10\n" +
	"\x0e_thumbnail_url\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\x18AddAccomplishmentRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"-\n" +
	"\x1bDeleteAccomplishmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x9f\x03\n" +
	"\x0fProfilesService\x123\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\r.auth.Profile\x12A\n" +
	"\x0fUpgradeToAuthor\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x0fDowngradeToUser\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x121\n" +
	"\tGetAuthor\x12\x16.auth.GetAuthorRequest\x1a\f.auth.Author\x12K\n" +
	"\x11AddAccomplishment\x12\x1e.auth.AddAccomplishmentRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x14DeleteAccomplishment\x12!.auth.DeleteAccomplishmentRequest\x1a\x16.google.protobuf.EmptyB\x03Z\x01.b\x06proto3"

var (
	file_profiles_proto_rawDescOnce sync.Once
	file_profiles_proto_rawDescData []byte
)

func file_profiles_proto_rawDescGZIP() []byte {
	file_profiles_proto_rawDescOnce.Do(func() {
		file_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profiles_proto_rawDesc), len(file_profiles_proto_rawDesc)))
	})
	return file_profiles_proto_rawDescData
}

var file_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_profiles_proto_goTypes = []any{
	(*Profile)(nil),                     // 0: auth.Profile
	(*Author)(nil),                      // 1: auth.Author
	(*Course)(nil),                      // 2: auth.Course
	(*File)(nil),                        // 3: auth.File
	(*GetAuthorRequest)(nil),            // 4: auth.GetAuthorRequest
	(*AddAccomplishmentRequest)(nil),    // 5: auth.AddAccomplishmentRequest
	(*DeleteAccomplishmentRequest)(nil), // 6: auth.DeleteAccomplishmentRequest
	(*emptypb.Empty)(nil),               // 7: google.protobuf.Empty
}
var file_profiles_proto_depIdxs = []int32{
	3,  // 0: auth.Profile.image:type_name -> auth.File
	1,  // 1: auth.Profile.author_profile:type_name -> auth.Author
	2,  // 2: auth.Profile.courses:type_name -> auth.Course
	0,  // 3: auth.Author.user_profile:type_name -> auth.Profile
	3,  // 4: auth.Author.accomplishments:type_name -> auth.File
	3,  // 5: auth.Course.video:type_name -> auth.File
	3,  // 6: auth.Course.image:type_name -> auth.File
	1,  // 7: auth.Course.author:type_name -> auth.Author
	7,  // 8: auth.ProfilesService.GetProfile:input_type -> google.protobuf.Empty
	7,  // 9: auth.ProfilesService.UpgradeToAuthor:input_type -> google.protobuf.Empty
	7,  // 10: auth.ProfilesService.DowngradeToUser:input_type -> google.protobuf.Empty
	4,  // 11: auth.ProfilesService.GetAuthor:input_type -> auth.GetAuthorRequest
	5,  // 12: auth.ProfilesService.AddAccomplishment:input_type -> auth.AddAccomplishmentRequest
	6,  // 13: auth.ProfilesService.DeleteAccomplishment:input_type -> auth.DeleteAccomplishmentRequest
	0,  // 14: auth.ProfilesService.GetProfile:output_type -> auth.Profile
	7,  // 15: auth.ProfilesService.UpgradeToAuthor:output_type -> google.protobuf.Empty
	7,  // 16: auth.ProfilesService.DowngradeToUser:output_type -> google.protobuf.Empty
	1,  // 17: auth.ProfilesService.GetAuthor:output_type -> auth.Author
	7,  // 18: auth.ProfilesService.AddAccomplishment:output_type -> google.protobuf.Empty
	7,  // 19: auth.ProfilesService.DeleteAccomplishment:output_type -> google.protobuf.Empty
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_profiles_proto_init() }
func file_profiles_proto_init() {
	if File_profiles_proto != nil {
		return
	}
	file_profiles_proto_msgTypes[0].OneofWrappers = []any{}
	file_profiles_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profiles_proto_rawDesc), len(file_profiles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiles_proto_goTypes,
		DependencyIndexes: file_profiles_proto_depIdxs,
		MessageInfos:      file_profiles_proto_msgTypes,
	}.Build()
	File_profiles_proto = out.File
	file_profiles_proto_goTypes = nil
	file_profiles_proto_depIdxs = nil
}
